### ISSUE TITLE
cleaning up branches

### ISSUE THREAD

**Issue by shajoezhu** [luntergroup/scrm_jz_stable_branch#4]
Hi Gerton and Donna

I am thinking of also to clean up some of the branches here.

I think branches jz and jz_stable are quite outdated. I don't recall they were further updated since last year I updated scrm into this folk. 

after the update, I have used smcsmcScrm as the master branch for this folk.

since the update, I have been using scrmScrm branch to keep track for the master branch of scrm, I am trying to remember the reason why I did this at the first place. 

delayed_IS_scrm seems to be updated, but not in use any longer. 

multi_tiered_focus is further extending smcsmcScrm, it doesn't seem to conflict with anything in smcsmcScrm

decouplePruningAndTimeInterval was last updated a year ago. I don't know what to do with it yet. 

I propose we
 - [x] change this folk name to smcsmcScrm
 - [x] use smcsmcScrm as the master branch for this folk
 - [x] merge multi_tiered_focus to smcsmcScrm
 - [x] remove branches jz, jz_stable and delayed_IS_scrm 

Please let me know what do you think. :)

Best
Joe

**Comment by gerton** [comment]
Sounds good to me.

BW
Gerton

**Comment by DonnaHenderson** [comment]
Yes, I agree with that plan.

Best,
Donna

On 4 Dec 2016, at 10:10, gerton <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds good to me.

BW
Gerton

**Comment by shajoezhu** [comment]
need to change 

1 .gitmodules
```
[submodule "src/scrm"]
        path = src/scrm
        url = https://github.com/luntergroup/smcsmcScrm.git
```
git submodule sync

2. scrm
```
joezhu@joezhu-M3800:~/smcsmc/src/scrm$ git remote -v
origin	https://github.com/luntergroup/smcsmcScrm.git (fetch)
origin	https://github.com/luntergroup/smcsmcScrm.git (push)
upstream	https://github.com/scrm/scrm/ (fetch)
upstream	https://github.com/scrm/scrm/ (push)
```

**Comment by shajoezhu** [comment]
branch 'multi_tiered_focus' is now ready to be removed

**Comment by shajoezhu** [comment]
Hi Gerton

I don't have admin privilege to change the repo name to smcsmcScrm. I was wondering could you grant me the permission? or shall I do this next time when we meet.

Best
Joe

**Comment by gerton** [comment]
Hi Joe,

Sorry, I forgot to respond to this email earlier.  I think I’ve given you the right permissions now; let me know if I need to change somethign else.

Best wishes
Gerton

**Comment by shajoezhu** [comment]
Thanks Gerton. 

submodule repo updated, merged, renamed, synced (see https://github.com/luntergroup/smcsmc/pull/60)

Do you mind I remove branch multi_tiered_focus now?
